### ISSUE TITLE
"yo webapp" throws TypeError: Cannot read property 'bold' of undefined

### ISSUE THREAD

**Issue by simonsilvalauinger** [yeoman/generator-webapp_DEPRECATED#137]
Hi,
after installing with "npm install -g generator-webapp" I executed "yo webapp" and the following error occured:

> yo webapp

TypeError: Cannot read property 'bold' of undefined
    at Object.<anonymous> (C:\Users\simon\AppData\Roaming\npm\node_modules\generator-webapp\node_modules\yeoman-generator\lib\util\common.js:5:56)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\simon\AppData\Roaming\npm\node_modules\generator-webapp\node_modules\yeoman-generator\lib\base.js:91:26)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

May somebody help me?
Thanks,
Simon

**Comment by sindresorhus** [comment]
Should be fixed now. Just `npm cache clean` and reinstall the generator.

**Comment by sjmog** [comment]
This isn't fixed for me. Cache cleaned, npm reinstalled, still the same issue.

**Comment by rajbala** [comment]
I'm also seeing the same issue.  I have npm 1.3.8 and node 0.10.17 installed.

**Comment by stephenplusplus** [comment]
Can you guys try `$ npm cache clean && npm uninstall -g yeoman-generator && npm install -g yeoman-generator` just for the heck of it :)

**Comment by aautio** [comment]
@stephenplusplus I tried that - did not help. Still getting the problem after a fresh install.

**Comment by jmhmd** [comment]
Same issue with `yo express`. Fresh install of yeoman, also using angular generator for what it's worth, which worked fine. Tried `npm cache clean` and reinstalling as well.

**Comment by passy** [comment]
If this still happens, it can only be because a particular generator hasn't been updated. Please open a new issue there.

**Comment by robwierzbowski** [comment]
@sindresorhus What commit was this fixed in?

**Comment by kevva** [comment]
@robwierzbowski, have a look at commits in [yeoman/generator](https://github.com/yeoman/generator) and [yeoman/yo](https://github.com/yeoman/yo). It's probably this one yeoman/generator@3c60110 for this issue.

**Comment by robwierzbowski** [comment]
Thanks @kevva.

**Comment by durp** [comment]
For TypeError: Cannot read property 'bold' of undefined
Looks like a cute little ascii art is the culprit...

yeoman-generator/lib/util/common.js:5
'\n   `---------´  |    ' + 'Welcome to Yeoman,'.yellow.bold + '    |' +
                                                       ^
TypeError: Cannot read property 'bold' of undefined
    at Object.<anonymous> (/usr/local/share/npm/lib/node_modules/generator-karma/node_modules/yeoman-generator/lib/util/common.js:5:56)

As a workaround, just set

module.exports.yeoman = 'Yo!'

**Comment by robwierzbowski** [comment]
Yep, that's the issue. It's replaced with the generator provided ASCII in the latest master.

On Sunday, August 25, 2013, Geoff Sindel wrote:

> For TypeError: Cannot read property 'bold' of undefined
> Looks like a cute little ascii art is the culprit...
> 
> yeoman-generator/lib/util/common.js:5
> '\n `---------´ | ' + 'Welcome to Yeoman,'.yellow.bold + ' |' +
> ^
> TypeError: Cannot read property 'bold' of undefined
> at Object.
> (/usr/local/share/npm/lib/node_modules/generator-karma/node_modules/yeoman-generator/lib/util/common.js:5:56)
> 
> As a workaround, just set
> 
> module.exports.yeoman = 'Yo!'
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/yeoman/generator-webapp/issues/137#issuecomment-23236847
> .

## 

Rob Wierzbowski
@robwierzbowski http://twitter.com/#!/robwierzbowski
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by kevva** [comment]
@durp, see my comment above. This was fixed and should be working. If it isn't you might try clearing the cache and installing generator-webapp again.

**Comment by JacopKane** [comment]
Same here, cleaning cache and reinstalling didn't solve the issue.
Getting the same error with all generators.

```
/usr/local/share/npm/lib/node_modules/generator-gruntfile/node_modules/yeoman-generator/lib/util/common.js:5
'\n   `---------´  |    ' + 'Welcome to Yeoman,'.yellow.bold + '    |' +
                                                       ^
TypeError: Cannot read property 'bold' of undefined
```

**Comment by kevva** [comment]
@JacopKane, yes, you will get this with some generators, like the gruntfile one because we haven't published a new release on that one yet. The webapp generator should work though.

**Comment by jarrodpayne** [comment]
This line alone didn't work for me

```
npm cache clean && npm uninstall -g yeoman-generator && npm install -g yeoman-generator
```

But, after that, I ran

```
npm uninstall -g generator-webapp
```

```
npm install -g generator-webapp
```

And, all was well to run `yo webapp`

**Comment by kevva** [comment]
Yup, that's what I've been telling you to do :).

> ...you might try clearing the cache and installing generator-webapp again.

You don't have to install `yeoman-generator` at all since it's mostly used as a dependency.

**Comment by jarrodpayne** [comment]
@kevva Yep, your the reason I reinstalled `generator-webapp`. I figured it would be nice to show people the commands directly.

**Comment by sjmog** [comment]
OK, now to trawl through all the community generators and cry havoc with some ascii art.

**Comment by JacopKane** [comment]
@kevva Oh okay, probably I've got all the outdated generators.
The `generator-webapp` is indeed working now after reinstall.
Thanks.

**Comment by Marak** [comment]
Yep. This is what happens when you decide to rewrite and replace dependencies for your project without taking the small amount of time to actually contribute back to them.

These same guys made a mess over at the `colors` repo before messing up `yeoman` with this.

So...much..wasted...time...

**Comment by e-oz** [comment]
So stupid time wasting. For some useless colors.

**Comment by cmawhorter** [comment]
o 0  ... so much anger in here.... I demand a refund!  ... oh wait.

Thanks to @jpdesigndev for the copy/pasteable commands.  Worked for me.

**Comment by mulderp** [comment]
- 1

As quick fix, I edited the file and replaced:

   'Welcome to Yeoman,'.yellow.bold+

with 'yellow'

This works but gives

<pre>
     _-----_
    |       |
    |undefined|   .--------------------------.
   `---------´  |    undefined    |
    undefined_undefined_undefined   |   undefined  |
    /___A___\   '__________________________'undefined
   __undefined__
 ´   undefined° undefined `
</pre>

**Comment by kevva** [comment]
@mulderp, it should look like this https://github.com/yeoman/generator/blob/master/lib/util/common.js. Or even better, update the generator.

**Comment by mulderp** [comment]
Thanks for that link! Also, I switched to an updated generator an then it works great!

**Comment by darlanalves** [comment]
Hey guys: I've tried the reinstall command and it failed, then I found out that the generator-karma was messing with the whole dependency tree. Uninstalling generator-karma and installing generator-angular right after has done the trick.

**Comment by kuryaki** [comment]
i got this error and worked around this editing the problem generator
sudo vim /usr/local/lib/node_modules/generator-deckjs/node_modules/yeoman-generator/lib/util/common.js

removed everything .bold, got a funny yeoman but it worked

**Comment by kevva** [comment]
@kuryaki, send a PR to https://github.com/dvberkel/generator-deckjs with an update to the `yeoman-generator` dependency.

**Comment by kuryaki** [comment]
@kevva https://github.com/yeoman/generator-webapp/issues/137#issuecomment-25033771 is what i did im guessing yo people are not going to take a pr that takes away their beautiful yellow

**Comment by kevva** [comment]
@kuryaki, we have already fixed this issue on our generators. The reason it's happening is because we moved away from `colors.js` to `chalk`which has another API. Those generators who hasn't updated their `yeoman-generator` dependency to `~13.0.0` will suffer from this error.

**Comment by marsbergen** [comment]
You mean ~0.13.0 I assume :)

**Comment by kevva** [comment]
Whops, yeah, I do :).
