### ISSUE TITLE
Error running grunt with new webapp and default options

### ISSUE THREAD

**Issue by kyen99** [yeoman/generator-webapp_DEPRECATED#140]
With a clean install of yo and webapp and a newly created webapp project using default settings with all three options selected, I get the following build error when running grunt:

```
...
Running "concurrent:dist" (concurrent) task

    Running "htmlmin:dist" (htmlmin) task
    File dist/404.html created.
    File dist/index.html created.

    Done, without errors.

    Elapsed time
    htmlmin       4s
    htmlmin:dist  79ms
    Total         4s

    Running "copy:styles" (copy) task


    Done, without errors.

    Elapsed time
    copy:styles  4s
    Total        4s
        Warning: 
    /Users/kyen/Sites/test/node_modules/grunt-contrib-compass/node_modules/tmp/lib/tmp.js:261
      throw err;
            ^
    Error: ENOENT, no such file or directory 'dist/images/glyphicons-halflings-white.png'
        at Object.fs.statSync (fs.js:684:18)
        at processed (/Users/kyen/Sites/test/node_modules/grunt-contrib-imagemin/tasks/imagemin.js:80:43)
        at /Users/kyen/Sites/test/node_modules/grunt-contrib-imagemin/tasks/imagemin.js:127:29
        at callDone (/Users/kyen/Sites/test/node_modules/grunt/lib/grunt/util.js:147:5)
        at ChildProcess.<anonymous> (/Users/kyen/Sites/test/node_modules/grunt/lib/grunt/util.js:186:5)
        at ChildProcess.EventEmitter.emit (events.js:98:17)
        at maybeClose (child_process.js:735:16)
        at Socket.<anonymous> (child_process.js:948:11)
        at Socket.EventEmitter.emit (events.js:95:17)
        at Pipe.close (net.js:466:12) Used --force, continuing.

    Running "imagemin:dist" (imagemin) task
...
```

At this point dist/images has just glyphicons-halflings.png.tmp.  I did confirm that app/images has glyphicons-halflings-white.png.

This is using...
osx 10.6.8
node 0.10.17
npm 1.3.8
yo 1.0.3
generator-webapp 0.3.1

I also did the following to make sure install is clean:

```
npm cache clean
npm uninstall -g yo webapp-generator
npm install -g yo webapp-generator
```

I also tried running `grunt server` first to see if that would help.

The only errors I see anywhere in the install of yo, webapp or creating the webapp is with pngquant that says initial tests fail, but then it appears to be downloaded from source and built successfully.

**Comment by kyen99** [comment]
Downgrading grunt-contrib-imagemin to 0.1.4 fixes the problem so looks like it might be an issue with grunt-contrib-imagemin@0.2.0.

**Comment by schickling** [comment]
Same here using https://github.com/yeoman/generator-angular  I think its because pngquant needs X11. Honestly, I don't want that on my system...

I also installed a previous version using `npm install grunt-contrib-imagemin@0.1.4`

**Comment by kyen99** [comment]
I don't think it's an X11 dependency because I have the X11 subsystem on my Mac and the build still fails.

**Comment by kevva** [comment]
sindresorhus/node-pngquant-bin#5

**Comment by sindresorhus** [comment]
Should be fixed now.

**Comment by SgtPooki** [comment]
I don't believe this is fixed. I'm getting these issues on Debian 7.1 with a fresh install of npm, node, and yeoman, for both gifsicle and pngquant. See https://github.com/isaacs/npm/issues/4014

I did have to downgrade npm to 1.2.10 to get the install to not freak out. See https://github.com/yeoman/yeoman/issues/929.

I've tried generator-webapp, generator-angular, generator-angularjs, and all have failed because of pngquant and gifsicle. I just tried generator-ng-require and its the only one that has worked successfully, I assume because it's not using imagemin.

Is there some way to install a generator, such as webapp, have it fail, and then edit the package.json to remove the problem dependency? I tried removing imagemin from package.json and started getting "npm WARN prefer global bower@1.2.7 should be installed with -g".

**Comment by emardini** [comment]
It is weird but it only breaks for some png, I have a folder with 4 png's and it only breaks for one particular file. Downgrading to 0.1.4 fixed my problem.

**Comment by ain** [comment]
Not fixed, should be reopened. Latest version installed, still throws up on: 

`/Users/…/node_modules/grunt-contrib-compass/node_modules/tmp/lib/tmp.js:261`

**Comment by yveson33** [comment]
Same issue, fresh install of yo, npm and got same errors

**Comment by toaotc** [comment]
Same issue here

**Comment by lovettbarron** [comment]
Likewise, same issue.
  /Users/readywater/src/shop/nov-tiles/node_modules/grunt-contrib-compass/node_modules/tmp/lib/tmp.js:261
      throw err;
            ^
    Error: ENOENT, no such file or directory 'dist/images/07m.jpg'

**Comment by iamcoreyg** [comment]
Having the same issue..

**Comment by zenorocha** [comment]
+1 here

**Comment by jonadeline** [comment]
Not better here.

**Comment by tabakd** [comment]
Same.

**Comment by thewalkingtoast** [comment]
The happens because when the project is generated, the absolute path to
phantom on your system is hard coded into a config file. Moving the project
to a different directory triggers the problem.

See
https://github.com/yeoman/generator-webapp/issues/146#issuecomment-23770794

**Comment by kobkrit** [comment]
Same here

```
/Users/kobkrit/git/fonBrand/node_modules/grunt-contrib-compass/node_modules/tmp/lib/tmp.js:261
  throw err;
        ^
Error
    at new JS_Parse_Error (/Users/kobkrit/git/fonBrand/node_modules/grunt-modernizr/node_modules/uglify-js/lib/parse-js.js:263:22)
    at js_error (/Users/kobkrit/git/fonBrand/node_modules/grunt-modernizr/node_modules/uglify-js/lib/parse-js.js:271:15)
    at parse_error (/Users/kobkrit/git/fonBrand/node_modules/grunt-modernizr/node_modules/uglify-js/lib/parse-js.js:367:17)
    at Object.next_token [as input] (/Users/kobkrit/git/fonBrand/node_modules/grunt-modernizr/node_modules/uglify-js/lib/parse-js.js:613:17)
    at next (/Users/kobkrit/git/fonBrand/node_modules/grunt-modernizr/node_modules/uglify-js/lib/parse-js.js:718:37)
    at Object.parse (/Users/kobkrit/git/fonBrand/node_modules/grunt-modernizr/node_modules/uglify-js/lib/parse-js.js:704:19)
    at uglify (/Users/kobkrit/git/fonBrand/node_modules/grunt-modernizr/node_modules/uglify-js/uglify-js.js:7:17)
    at Object._Gruntifier.finalize (/Users/kobkrit/git/fonBrand/node_modules/grunt-modernizr/lib/gruntifier.js:457:13)
    at Object.<anonymous> (/Users/kobkrit/git/fonBrand/node_modules/grunt-modernizr/lib/gruntifier.js:426:11)
    at notify (/Users/kobkrit/git/fonBrand/node_modules/grunt-modernizr/node_modules/promised-io/promise.js:201:22)
```

**Comment by jonadeline** [comment]
On my side , I get the following error randomly on livereload : 

```
/Volumes/HDD2/Jonathan/Google Drive/CafeMerling/node_modules/grunt-contrib-compass/node_modules/tmp/lib/tmp.js:261
  throw err;
        ^
Error: socket hang up
    at createHangUpError (http.js:1360:15)
    at ServerResponse.OutgoingMessage._writeRaw (http.js:507:26)
    at ServerResponse.OutgoingMessage._send (http.js:476:15)
    at ServerResponse.OutgoingMessage.write (http.js:749:16)
    at ondata (stream.js:38:26)
    at EventEmitter.emit (events.js:96:17)
    at ReadStream._emitData (fs.js:1368:10)
    at afterRead (fs.js:1350:10)
    at fs.read.callback (/Volumes/HDD2/Jonathan/Google Drive/CafeMerling/node_modules/grunt-contrib-imagemin/node_modules/gifsicle/node_modules/bin-wrapper/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/fstream/node_modules/graceful-fs/polyfills.js:207:17)
    at fs.read.callback (/Volumes/HDD2/Jonathan/Google Drive/CafeMerling/node_modules/grunt-contrib-imagemin/node_modules/gifsicle/node_modules/bin-wrapper/node_modules/download/node_modules/decompress/node_modules/rimraf/node_modules/graceful-fs/polyfills.js:207:17)
    at fs.read.callback (/Volumes/HDD2/Jonathan/Google Drive/CafeMerling/node_modules/grunt-contrib-imagemin/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/fstream/node_modules/graceful-fs/polyfills.js:207:17)
```

**Comment by johnsmeeth** [comment]
The same issue to me

**Comment by addyosmani** [comment]
Reopened due to the number of reports about this still failing. Re-confirming whether the issue is still a problem on Mac/Linus with the latest version now.

**Comment by johnking-ca** [comment]
Same to me! Fresh installations for all packages.

**Comment by johnking-ca** [comment]
Added screen shot: 

```
/home/king/Apps/yo_ng/node_modules/grunt-contrib-compass/node_modules/tmp/lib/tmp.js:261
  throw err;
        ^
RangeError: An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template ....
```

**Comment by lucascaton** [comment]
+1

**Comment by omanizer** [comment]
+1

**Comment by koalajoe23** [comment]
EDIT: Nevermind, I fixed it by instzalling the compass gem

**Comment by eddiemonge** [comment]
Is this still affecting people? If so, could you post your version of node, npm, yo and the generator-webapp please?

**Comment by HuaHub** [comment]
Yes. Somehow it works once in a while, like if I log out and in.

npm -v: 1.3.25
node -v: v0.10.25
yo -v: 1.1.2

I used "yo angular" with sass and compass. Don't know if relevant, but here is some more info:
ruby 2.1.0p0
Compass 0.12.2

**Comment by eddiemonge** [comment]
@HuaHub what do you mean log out and in? What error are you getting exactly? Can you paste it to gist.github.com?

**Comment by HuaHub** [comment]
Sorry, log in and out of ubuntu, or reboot ubuntu.

It's nothing new from what pasted by @johnking-ca above: https://gist.github.com/HuaHub/8660505

Don't know if "npm cache clean" affects it, but I think I saw it a solution for some on stackoverflow. As well as the "gem install compass" solution. My problem still persists even though i tried both.

Edit: Before all the spam you see in the gist shows up, it spams first:
Running "watch" task
Waiting...Warning: watch ENOSPC

**Comment by eddiemonge** [comment]
what command are you running to get that output?

**Comment by HuaHub** [comment]
grunt serve

**Comment by eddiemonge** [comment]
what happens if you manually run a sass watch task without grunt?

**Comment by HuaHub** [comment]
What is the syntax for that?

**Comment by eddiemonge** [comment]
sass --watch app/css:.tmp/css

**Comment by HuaHub** [comment]
> > > Sass is watching for changes. Press Ctrl-C to stop.
> > >       error No such file or directory @ rb_sysopen - app/styles/css

**Comment by eddiemonge** [comment]
are you using the actual paths to your sass files?

**Comment by HuaHub** [comment]
I went into the styles directory and tried again now. Don't know where to specify the tmp folder.

sass --watch main.css:.tmp/css

> > > Sass is watching for changes. Press Ctrl-C to stop.
> > >       error main.css (Line 44: Inconsistent indentation: 2 spaces were used for indentation, but the rest of the document was indented using 8 spaces.)

 I'm at #yeoman @freenode as "huahax" if you want live chat.

**Comment by eddiemonge** [comment]
is this still an issue?

**Comment by HuaHub** [comment]
Yes

**Comment by HuaHub** [comment]
This is absurd, but it seems that running spotify bugs "grunt serve". Would you mind trying this @omanous, @lucascaton, @johnking-ca if you still have this issue?

**Comment by ain** [comment]
FYI: There're no such problems with `grunt-sass`. We switched to a libsass implementation a while ago over the performance on livereload.

**Comment by eddiemonge** [comment]
@HuaHub spotify as in the music app Spotify?

@ain when libsass becomes more stable, this will be switched. `grunt-sass` was written by @sindresorhus, who is a core contributor to Yeoman

> Note that node-sass is currently under heavy development and might be unstable, there are also some stuff missing, like a compression option. Check out grunt-contrib-sass (based on Ruby Sass) if you want something stable that also supports the old syntax, but in turn much slower.

**Comment by HuaHub** [comment]
Yes, I'd be happy to show you if you know some screen sharing software.

**Comment by eddiemonge** [comment]
you could record your screen with the problem. and google hangouts has screen sharing

**Comment by ThiagoMiranda** [comment]
+1

**Comment by danielbeeke** [comment]
wierd... https://github.com/yeoman/generator-webapp/issues/140#issuecomment-34611379

is right,
the program spotify (the audio app) is making grunt crash.

I am on ubuntu 13.10 using 

grunt-cli v0.1.13
grunt v0.4.2
yo 1.1.2
Compass 1.0.0.alpha.18

**Comment by vladikoff** [comment]
Can't reproduce this in OS X, Is this Ubuntu only issue?

**Comment by vladikoff** [comment]
Can't reproduce this on 13.04
![image](https://f.cloud.github.com/assets/128755/2236739/1b3d951e-9b69-11e3-8fc0-9e707e6b0cc0.png)

Could it be a 13.10 issue?

**Comment by HuaHub** [comment]
I'm using 13.04. Perhaps it has something to do with how Spotify is installed. I used this method: http://www.omgubuntu.co.uk/2013/01/how-to-install-spotify-in-ubuntu-12-04-12-10

**Comment by danielbeeke** [comment]
I used: https://www.spotify.com/nl/download/previews/

rvm 1.25.15 (stable)
and nvm, but I can't find the version of that.

Maybe it has to do something with an EXPORT variable.
A couple of months I had an issue a lot like this.
Than I set some variable that had to do with maximum functions/templates and it worked.
So what I am guessing is that spotify sets some variables.

The bug happens when spotify is playing, and I start grunt, but when I start spotify after grunt there is no bug.

**Comment by vladikoff** [comment]
@danielbeeke @HuaHub have you looked at solving the ENOSPC error? http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc

**Comment by HuaHub** [comment]
Wow, I think that actually solved the problem. Thanks!
So it turns out that the problem is neither grunt or yeomans fault (?)...

**Comment by vladikoff** [comment]
Just to update this, seems like the reported issues may be caused by one of these:

Invalid template strings, see https://github.com/gruntjs/grunt-contrib-watch/issues/299 

FS Watch limit, see:
http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc

**Comment by silvenon** [comment]
Is this still an issue then?

**Comment by danielbeeke** [comment]
Not for me, limit var fixed it for me.

**Comment by eddiemonge** [comment]
haven't heard from OP and not a lot of activity recently so Im closing it.

**Comment by rizkysyazuli** [comment]
is there any fix yet? it's still broken on my side. i have an existing project and a fresh install just to test this. the fresh installation fails with a single png image.

i'm skipping imagemin for now and move all the image via the `copy:dist` task.

```
Running "clean:dist" (clean) task
Cleaning .tmp...OK
Cleaning dist/images...OK

Running "useminPrepare:html" (useminPrepare) task
Going through app/index.html to update the config
Looking for build script HTML comment blocks

Configuration is now:

  concat:
  { generated: 
   { files: 
      [ { dest: '.tmp/concat/styles/vendor.css', src: [] },
        { dest: '.tmp/concat/styles/main.css',
          src: [ '.tmp/styles/main.css' ] },
        { dest: '.tmp/concat/scripts/vendor/modernizr.js',
          src: [ 'bower_components/modernizr/modernizr.js' ] },
        { dest: '.tmp/concat/scripts/vendor.js',
          src: [ 'bower_components/jquery/dist/jquery.js' ] },
        { dest: '.tmp/concat/scripts/main.js',
          src: [ '{app,.tmp}/scripts/main.js' ] } ] } }

  uglify:
  { generated: 
   { files: 
      [ { dest: 'dist/scripts/vendor/modernizr.js',
          src: [ '.tmp/concat/scripts/vendor/modernizr.js' ] },
        { dest: 'dist/scripts/vendor.js',
          src: [ '.tmp/concat/scripts/vendor.js' ] },
        { dest: 'dist/scripts/main.js',
          src: [ '.tmp/concat/scripts/main.js' ] } ] } }

  cssmin:
  { generated: 
   { files: 
      [ { dest: 'dist/styles/vendor.css',
          src: [ '.tmp/concat/styles/vendor.css' ] },
        { dest: 'dist/styles/main.css',
          src: [ '.tmp/concat/styles/main.css' ] } ] } }

Running "concurrent:dist" (concurrent) task

    Running "copy:styles" (copy) task


    Done, without errors.


    Execution Time (2014-07-29 04:20:05 UTC)
    loading tasks   6ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇ 26%
    copy:styles    16ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 70%
    Total 23ms
        Warning: Running "imagemin:dist" (imagemin) task
    Warning: Bad argument Use --force to continue.
    TypeError: Bad argument
        at ChildProcess.spawn (child_process.js:923:24)
        at exports.spawn (child_process.js:723:9)
        at spawn (/Users/rizky/Sites/yeoman-webapp/node_modules/grunt-contrib-imagemin/node_modules/image-min/node_modules/win-spawn/index.js:54:10)
        at Imagemin._optimizePng (/Users/rizky/Sites/yeoman-webapp/node_modules/grunt-contrib-imagemin/node_modules/image-min/index.js:135:12)
        at Imagemin.optimize (/Users/rizky/Sites/yeoman-webapp/node_modules/grunt-contrib-imagemin/node_modules/image-min/index.js:40:19)
        at module.exports (/Users/rizky/Sites/yeoman-webapp/node_modules/grunt-contrib-imagemin/node_modules/image-min/index.js:149:21)
        at async.forEachLimit.msg (/Users/rizky/Sites/yeoman-webapp/node_modules/grunt-contrib-imagemin/tasks/imagemin.js:41:23)
        at replenish (/Users/rizky/Sites/yeoman-webapp/node_modules/grunt-contrib-imagemin/node_modules/async/lib/async.js:179:21)
        at /Users/rizky/Sites/yeoman-webapp/node_modules/grunt-contrib-imagemin/node_modules/async/lib/async.js:196:15
        at Object.async.eachLimit (/Users/rizky/Sites/yeoman-webapp/node_modules/grunt-contrib-imagemin/node_modules/async/lib/async.js:156:12)

    Aborted due to warnings.


    Execution Time (2014-07-29 04:20:05 UTC)
    loading tasks   7ms  ▇▇▇▇▇ 10%
    imagemin:dist  61ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 90%
    Total 68ms Use --force to continue.

        Aborted due to warnings.


Execution Time (2014-07-29 04:20:03 UTC)
concurrent:dist  2.4s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 99%
Total 2.4s
```

**Comment by budmc29** [comment]
After searching for hour and npm cache clean and npm install grunt-contrib-imagemin not working i found a solution:

> > npm cache clean && npm install gruntjs/grunt-contrib-imagemin
> > +
> > $ npm install --save imagemin-optipng (because i had an error and send it was missing optipng)

**Comment by JoanZapata** [comment]
For those, like me, who encountered this problem after the Yosemite update on a Mac, all you need to do is to reinstall compass with a `gem install compass`.

**Comment by salgua** [comment]
thank you @JoanZapata ! It worked for me!

**Comment by YonasBerhe** [comment]
RangeError: Maximum call stack size exceeded
This error keep coming up for me. Need help!!
