### ISSUE TITLE
bad grunt-contrib-htmlmin version + unspecified "error" event = yo death

### ISSUE THREAD

**Issue by jm3** [yeoman/generator-webapp_DEPRECATED#331]
generated package.json includes grunt-contrib-htmlmin 0.1.3 which breaks grunt:

```
...
grunt-contrib-htmlmin: ~0.1.3
```

yo webapp output:

```
npm ERR! Error: ENOENT, open '~/yo/node_modules/grunt-contrib-htmlmin/package.json'
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.6
npm ERR! errno 34
```

manually editing package.json to bring version to 0.2.0 fixes the above, but before that, `yo webapp` first dies loudly with the error message, `Uncaught, unspecified "error" event`:

```
✓ pre-build test passed successfully
npm ERR! not ok code 0 
events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at Appgenerator.EventEmitter.emit (events.js:74:15)
    at done (/usr/local/lib/node_modules/generator-webapp/node_modules/yeoman-generator/lib/base.js:318:16)
...
    at ChildProcess.EventEmitter.emit (events.js:117:20)
```

`yo webapp` output: [gist 9963917](https://gist.github.com/jm3/9963917)
`npm-debug.log`: [gist 9964012](https://gist.github.com/jm3/9964012)

**Comment by silvenon** [comment]
Which version of generator-webapp are you using? When I try with the latest (0.4.8), it works fine for me. Link the latest version:

```
git clone https://github.com/yeoman/generator-webapp
cd generator-webapp
npm link
```

and then try using `yo webapp` again. Did the issue go away?

**Comment by jm3** [comment]
Running the version out of github works, yes.

**Comment by TonyStark** [comment]
HI
I still get this "TypeError......" after trying by git clone....
here is my npm-debug.log>>http://pastebin.com/5MxQZmii
and i get error after running yo webapp

```
events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at Appgenerator.EventEmitter.emit (events.js:74:15)
    at done (/var/www/ProjecT/learn/grunt-example/generator-webapp/node_modules/yeoman-generator/lib/base.js:318:16)
    at /var/www/ProjecT/learn/grunt-example/generator-webapp/node_modules/yeoman-generator/node_modules/async/lib/async.js:232:13
    at /var/www/ProjecT/learn/grunt-example/generator-webapp/node_modules/yeoman-generator/node_modules/async/lib/async.js:113:21
    at /var/www/ProjecT/learn/grunt-example/generator-webapp/node_modules/yeoman-generator/node_modules/async/lib/async.js:24:16
    at /var/www/ProjecT/learn/grunt-example/generator-webapp/node_modules/yeoman-generator/node_modules/async/lib/async.js:229:17
    at /var/www/ProjecT/learn/grunt-example/generator-webapp/node_modules/yeoman-generator/node_modules/async/lib/async.js:516:34
    at Appgenerator.<anonymous> (/var/www/ProjecT/learn/grunt-example/generator-webapp/node_modules/yeoman-generator/lib/actions/install.js:43:7)
    at ChildProcess.EventEmitter.emit (events.js:117:20)
```

**Comment by silvenon** [comment]
Which options did you select? You're using Linux, right? Which distribution?

**Comment by silvenon** [comment]
Also, you seem to have ran `yo webapp` in a `generator-webapp` directory, I hope it was a new empty directory and not the cloned one? I might also have read the log file wrong.

**Comment by TonyStark** [comment]
Thanx for quick reply...

```
Which options did you select? You're using Linux, right? Which distribution?
```

I m using Ubuntu 13.10

```
Also, you seem to have ran yo webapp in a generator-webapp directory, I hope it was a new empty directory and not the cloned one? I might also have read the log file wrong.
```

Ya it was my mistake to ran `yo webapp` in generator-webapp cloned directory,
So i create new dir and ran `yo webapp`  but still get same error.
However i have also get npm errr every time due to privillage of root, npm work with sudo command.
so is that origin of TypeError too?

**Comment by silvenon** [comment]
Again, which options did you select? First you choose "Bootstrap", "Sass" and "Modernizr", next you choose whether you want libsass or not.

Yes, privileges might be the reason, but I'm not an expert of those. It sure sounds bad if you get errors every time you run npm, are you new to Node.js? Let's try some other things first.

When you ran `yo webapp` in `generator-webapp` did you delete files which may have been generated? Go in `generator-webapp` and run `git status` to see if anything has changed. Run `git co .` if you see any modified files in the output from `git status`. Also, if there are any untracked files, delete too, because `git co .` won't take care of those. After all that run `git status` again to check if everything is clean.

Try now.

**Comment by jm3** [comment]
fails on clean install, but you closed the bug? :)

On Monday, April 7, 2014, Kevin Mårtensson notifications@github.com wrote:

> Closed #331 https://github.com/yeoman/generator-webapp/issues/331.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/yeoman/generator-webapp/issues/331
> .

## 

jm3

Sent from a book.

**Comment by TonyStark** [comment]
@silvenon 
Hmm.
before mistake my generator-webapp is overwritten by "yo webapp" command
ok now delete everything and start from first. Also delete (npm remove -g generator-webapp)
now again `git clone https://github.com/yeoman/generator-webapp`
then `cd generator-webapp`
`sudo npm link`
NPM Done without any Error...
now `cd ../ && mkdir 123 && cd 123`
`yo webapp`
[?] What more would you like? (Press <space> to select)
‣⬢ Bootstrap
After selecting bootstrap,, here is my complete log: http://pastebin.com/7cc3WWgR

Well in above log there is lots of npm Errr, because of `npm install` command work by `sudo`.
this is common because i also install mocha, zf5 generator and same npm errr but not TypeError,  after `sudo npm install` i get packages in node_modules directory..
I get TypeError only in angular, webapp generator.
Well i am also new in Nodejs.... :)

**Comment by silvenon** [comment]
@jm3 It was closed because you said it works when you try from master. I think it will be reopened once we determine if this is a real issue.

@ax02798 Run `ls -la ~ | grep  .npm` and show me the output.

**Comment by jm3** [comment]
@silvenon which means that if someone follows the installation instructions on the homepage and does:

```
npm install -g generator-webapp
yo webapp
```

that the webapp generator won't work. I don't think it's likely that all new users will come here to read this closed bug report first :)

**Comment by silvenon** [comment]
Yes, you're right, but this error doesn't happen to me when I try with v0.4.8, which might mean there's something wrong with your setup. I still agree we should reopen this until we figure out exactly what's wrong. (@kevva)

**Comment by jm3** [comment]
cool. will it help if I reinstall node / npm from scratch and then run it
again?

On Tuesday, April 8, 2014, Matija Marohnić notifications@github.com wrote:

> Yes, you're right, but this error doesn't happen to me when I try with
> v0.4.8, which might mean there's something wrong with your setup. I still
> agree we should reopen this until we figure out exactly what's wrong. (
> @kevva https://github.com/kevva)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/yeoman/generator-webapp/issues/331#issuecomment-39908119
> .

## 

jm3

Sent from a book.

**Comment by TonyStark** [comment]
@silvenon 

``` sh
mac@ubuntu:~$ ls -la ~ | grep .npm
drwxr-xr-x 298 root root   32768 Apr  8 22:13 .npm
-rw-r--r--   1 mac  mac        1 Apr  8 19:44 .npmrc

```

**Comment by silvenon** [comment]
We found the problem! :D Type `chown mac ~/.npm` or `sudo chown mac ~/.npm` if the first command complains about permissions. Now try running `yo webapp` again. (In an empty directory :P)

**Comment by TonyStark** [comment]
@silvenon 
well this time npm work without sudo, but
Still getting.....
http://pastebin.com/Hcm8ujfg
i also note that in another package of angular
when i run `yo angular:main`
i get only

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Did not provide required argument name!
    at Generator.argument (/usr/local/lib/node_modules/generator-angular/node_modules/yeoman-generator/lib/base.js:260:31)
    at Generator.module.exports.Base.extend.constructor (/usr/local/lib/node_modules/generator-angular/node_modules/yeoman-generator/lib/named-base.js:20:10)
    at Generator (/usr/local/lib/node_modules/generator-angular/script-base.js:8:31)
    at new Generator (/usr/local/lib/node_modules/generator-angular/main/index.js:9:14)
    at Environment.create (/usr/local/lib/node_modules/yo/node_modules/yeoman-generator/lib/env/index.js:252:10)
    at Environment.run (/usr/local/lib/node_modules/yo/node_modules/yeoman-generator/lib/env/index.js:288:24)
    at init (/usr/local/lib/node_modules/yo/cli.js:95:7)
    at pre (/usr/local/lib/node_modules/yo/cli.js:113:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/cli.js:139:1)
    at Module._compile (module.js:456:26)
```

i think problem within yo installer

**Comment by silvenon** [comment]
Add `mac` permissions to `/home/mac/tmp` directory as well: `(sudo) chown mac /home/mac/tmp`, that's what npm uses as a temp directory and I bet it has the same wrong permissions.

Btw, you shouldn't use `sudo` for everything, just when it's needed, otherwise permission problems like this happen. I blame Linux for this, though.

`yo angular:main` fails for me as well, with the same error, that's a different issue. (yeoman/generator#521)

**Comment by silvenon** [comment]
@jm3 Sorry, I missed your question somehow. What OS are you using?

**Comment by TonyStark** [comment]
@silvenon 
YEAH !!!!
Finally solve it,
i follow `(sudo) chown mac /home/mac/tmp`
but still not work, so i search on google about `npm Errr`
and i follow this problem: http://stackoverflow.com/questions/20330273/error-installing-yeoman
and fix it...
now you can see my clear `yo webapp` log: http://pastebin.com/snC5f4yZ
Thanx again @silvenon :+1: :+1:

**Comment by TonyStark** [comment]
Well now `generator-webapp` has new version 0.4.9
updated...
now i enter  `grunt` it gives me 2 below error.
but i solved by copying (bower_components directory) `/web/app/bower_components` to `/web/bower_components`
i post this because may be someone got same problem so he can see how to fix this....

```
Looking for Modernizr references
Warning: Can't find your Modernizr development build at bower_components/modernizr/modernizr.js
       grunt-modernizr needs this path to avoid false positives

       Update your gruntfile via the modernizr.devFile config option
       See https://github.com/doctyper/grunt-modernizr#devfile-string for more details

       Use --force to continue.

Aborted due to warnings.
```

```
        Warning: Syntax error: File to import not found or unreadable: /bower_components/bootstrap-sass-official/vendor/assets/stylesheets/bootstrap.scss.
                  Load paths:
                    /var/www/ProjecT/learn/grunt-example/web (DEPRECATED)
                    /var/www/ProjecT/learn/grunt-example/web/app/styles
                    /var/www/ProjecT/learn/grunt-example/web/bower_components
            on line 4 of app/styles/main.scss
      Use --trace for backtrace. Use --force to continue.

        Aborted due to warnings.
```

**Comment by jm3** [comment]
@silvenon  OS X 10.9.2, node **v0.10.26** + npm **1.4.6** installed via the standard pkg installer.

```
Darwin jm3.local 13.1.0 Darwin Kernel Version 13.1.0: Thu Jan 16 19:40:37 PST 2014;
root:xnu-2422.90.20~2/RELEASE_X86_64 x86_64
```

**Comment by silvenon** [comment]
Oh, yes, good catch. `bower_components` was moved to the project's root. Glad you got this fixed! :smile: 

However, I think this issue still shouldn't be closed because I believe this wasn't related to @jm3's issue. @jm3, could you tell me which OS you are using and how you installed node and npm?

**Comment by jm3** [comment]
see previous comment ;)

**Comment by TonyStark** [comment]
@jm3 
in your both log the error is [ENOENT](https://github.com/joyent/node/blob/b3e4fc6a48b97b52bd19de43c76b7082dcab4988/test/simple/test-domain.js#L73) means,, file is not exist or path is wrong.
try [#3664](https://github.com/npm/npm/issues/3664#issuecomment-27550697)
`npm cache clean`
then `yo webapp`

**Comment by silvenon** [comment]
GitHub didn't show me that previous comment at the time :)

@rutull's solution doesn't work, try removing node and npm completely from your system and install them again. I recommend via Homebrew if you use it (`brew install node`), which had a flaw before where you couldn't update npm, but now the command installs npm separately, so you can later normally update npm with `npm update -g npm`.

Sorry if this is inconvenient for you, but I have no idea where else to start... but on the bright side, you'll have a better way to update node (`brew update && brew upgrade node`) :wink:

**Comment by jm3** [comment]
removing everything again and re-installing with `brew` fixed it. classic node!

thanks for the help :thumbsup:

**Comment by ccharlton** [comment]
<code>npm cache clean</code> fixed it for me, thanks.
